### ISSUE TITLE
Replace fixed strings in sensor.py to use language file

### ISSUE THREAD

**Issue by DejanBukovec** [petrleocompel/hikaxpro_hacs#13]
In sensor.py we need to change that some fixed strings use language file.

Slovenian translations:
Unknown					=		Neznan
Magnet presence			=		Prisotnost magneta
Temperature				=		Temperatura
Humidity					=		Vlažnost
Battery					=		Baterija
Signal					= 		Signal
Tamper					=		Sabotaža
Bypass					=		Obhod
Armed					=		Omogočen
Alarm					=		Alarm
Stay away				=		Omogočen zunaj
Is via repeater				=		Povezan preko ponavljalnika

**Comment by petrleocompel** [comment]
I understand. Sadly my knowledge is not that high so I have to look in HA Docs and search how to translate these attributes.

**Comment by DejanBukovec** [comment]
Maybe this help you:
https://developers.home-assistant.io/docs/internationalization/core/#entity-attribute-name-and-state-of-entity-components

**Comment by petrleocompel** [comment]
Found it already 😊. Just too much to focus on. It will take some time to make it right.

**Comment by petrleocompel** [comment]
So I am unsure if we should try... Even official integrations are not translated. 
<img width="708" alt="image" src="https://user-images.githubusercontent.com/9423543/221911193-a0ad4178-c2b4-4971-8c62-665d2ed4a869.png">

Also it is customizable.
So it is up to user to change and set it up
<img width="597" alt="image" src="https://user-images.githubusercontent.com/9423543/221911370-bc310873-dd37-4365-8ace-6eee328819c9.png">

I think if you agree until HA docs will say to do it we would keep the basics. Otherwise you can customize your entitites in HA yourself.

**Comment by DejanBukovec** [comment]
Ok no problem, then leave it as is :) I think that most or all integrations have fixed English name as Im quick check...

**Comment by petrleocompel** [comment]
Closing for now
