### ISSUE TITLE
Contact sensor magnet status switched around

### ISSUE THREAD

**Issue by praemon** [petrleocompel/hikaxpro_hacs#133]
Hi all. So I’ve been using this integration without issue for a while now (thanks to all the contributors!). I’ve since updated to 2.2.1 and noticed the magnet status has switched around on all my contact sensors (DS-PDMCS-EG2-WE(B)). ie. Closed doors show the magnet as “off” while open doors show as “on”. This has resulted in all linked automations failing.

Before I try uninstall and reinstall everything, is there anyway to reset the statuses so they get corrected? Or is this now the “correct” status for the magnet open/close status?

Thanks!

**Comment by petrleocompel** [comment]
So currently the magnet sensor was completely broken because it was for certain systems not respecting the value at all.

It is based on `PRESENCE` so it is might not good. And might should be based on type `SAFETY`.
But in all cases even `SAFETY` type says "off" = safe. And I think that is correct.

With `PRESENCE` - "On means home, Off means away." Which for this case does not mean much sense.

The logic even previously was even now it is `magnet_open_status` directly returned from Hikvision.
So open magnet = true. Closed = false.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/5cc2f6d1-26af-49c2-9a14-e0f1980694ac">

**Comment by petrleocompel** [comment]
I might will change the "type" to `SAFETY`. But the value will be according the documentation.

- "ON" = open
- "OFF" = closed

**Comment by petrleocompel** [comment]
Fixed type to match the documentation and released [v2.2.2](https://github.com/petrleocompel/hikaxpro_hacs/releases/tag/v2.2.2)

**Comment by nautilus7** [comment]
Hi, is it normal that my magnetic contact only show a status (online) sensor now? See picture:

![image](https://github.com/user-attachments/assets/eab7c140-2a43-489d-9904-d297891330dc)

With version 2.1.6 I had an extra sensor that got disabled with the 2.2.1 and 2.2.2. See picture of latest version before deleting the configuration and reloading:

![Screenshot 2024-10-14 232054](https://github.com/user-attachments/assets/d1572f01-a028-4777-93bb-5fa7eb0d2c98)


I am using the old ax panel (not the pro).
I have sent logs via email.
