### ISSUE TITLE
MultiInstance - Missing areas - duplicate IDs

### ISSUE THREAD

**Issue by ahmet8282** [petrleocompel/hikaxpro_hacs#141]
I have two alarm panels. They are both integrated.  They have almost identical setup.

One of them lists all areas as expected.

The other one only lists 3 out of 6.

What could be the reason of this?

**Comment by petrleocompel** [comment]
Sadly original integration did not even support areas and I really did not see a reason to have 1 HA aka 1 home to have multiple of security systems. 

Personally I use multiple HA for different locations. because then I can detect "position" of the person being "at home".

It can be fixed just right now but it will change the zones "ID" in HA.

**Comment by petrleocompel** [comment]
It will be probably some random of device system id md5 or something 
Or ip prefix/sufix. 
More stuff to configure = more problems

**Comment by petrleocompel** [comment]
It cannot be fully random because otherwise on each start of HA would change the "id" and all automatons of references would be broken. 
But as I wrote it will be sort of prefix. 
Maybe md5 of system ID of the device or just the plain system ID.

**Comment by petrleocompel** [comment]
But it will require release of version `3.0.0` it is breaking since the IDs are going to change

**Comment by petrleocompel** [comment]
I will do it today as "beta" release it will contain this + one more "chore" so you can test it. if it will be fine I can later release it as "stable"
