### ISSUE TITLE
sensor instead of binary_sensor

### ISSUE THREAD

**Issue by Sjeiz** [petrleocompel/hikaxpro_hacs#71]
Hi Peter,

thanks for your fantastic work!
Question: All my sensors appear as a normal sensor, instead of binary sensor.
eg Slim magnetic contact.
```python
class HikMagneticContactDetector(CoordinatorEntity, HikDevice, BinarySensorEntity):
```

As a result, color coding based on the state is not possible.

I've looked in the code, and they seem to be defined as binary sensor.
What am I missing?

Regards,
Erik

**Comment by petrleocompel** [comment]
Can you provide more info about where are you trying to color code the results of the sensors ? 

Because for me it is just implementation of BinarySernsorEntity and so far docs are pretty clear about it
https://www.home-assistant.io/integrations/binary_sensor/
https://developers.home-assistant.io/docs/core/entity/binary-sensor

**Comment by petrleocompel** [comment]
Closing - inactivity
